uploads = []
generated = []

[[outputs]]
id = "hGR9P4PeMCDdxbheDzOYn"
uri = "file://PROJECT_DETAILS.md"
type = "text"
title = "كاشير برو — ملف التفاصيل المهمة"

[[outputs]]
id = "dX4ak905yr8SaQ04LJ4_w"
uri = "file://CREDENTIALS.md"
type = "text"
title = "كاشير برو — أهم البيانات"
